# This Argo Workflow demonstrates the use of an emptyDir volume for sharing data between steps.
# The workflow creates a temporary directory that exists for the lifetime of the workflow pod.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: empty-dir- # Workflow name prefix
spec:
  entrypoint: main # The main entrypoint template
  volumes:
    - name: out
      emptyDir: {} # Define an emptyDir volume named 'out'
  templates:
    - name: main
      steps:
        - - name: generate-message
            template: generate-message
        - - name: echo-message
            template: echo-message
            arguments:
              parameters:
                - name: message
                  value: "{{steps.generate-message.outputs.parameters.message}}"

    - name: generate-message
      container:
        image: argoproj/argosay:v2 # Container image to run
        command: [sh, -c] # Shell command
        args: ["cowsay hello world | tee /mnt/out/hello_world.txt"] # Write output to a file in the mounted volume
        volumeMounts:
          - name: out # Mount the 'out' volume
            mountPath: /mnt/out # Mount path inside the container
      outputs:
        parameters:
          - name: message
            valueFrom:
              path: /mnt/out/hello_world.txt # Output parameter from the file created in the volume
    - name: echo-message
      inputs:
        parameters:
          - name: message
      script:
        image: alpine:latest
        command: [sh]
        source: |
          echo "Message from previous step:"
          echo "{{inputs.parameters.message}}"
