apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: data-processing-workflow-
spec:
  # must complete in 8h (28,800 seconds)
  activeDeadlineSeconds: 28800
  # keep workflows for 1d (86,400 seconds) i.e. delete workflows after 1 day
  ttlStrategy:
    secondsAfterCompletion: 86400
  # pod garbage collection
  podGC:
    strategy: OnWorkflowSuccess # delete pods after wf succeeds and leave behind on failures
  # avoid running pods as root user (default)
  securityContext:
    runAsNonRoot: true
    runAsUser: 8737 # any non-root user
  # retry pods that were deleted (e.g. due to node draining, accidental deletion etc)
  retryStrategy:
    retryPolicy: OnError
    limit: 1

  entrypoint: process-data
  arguments:
    parameters:
      - name: files
        value: '["file1.txt", "file2.txt", "file3.txt"]'
  templates:
    - name: process-data
      steps:
        - - name: invoke-process-data-template
            templateRef:
              name: data-processing-template
              template: process-data
            arguments:
              parameters:
                - name: files
                  value: "{{workflow.parameters.files}}"
