apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflows-cluster-access
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflows", "workflowtemplates", "cronworkflows", "clusterworkflowtemplates", "workfloweventbindings"]
  #resources: ["workflows"]
  verbs: ["get", "list", "watch", "create", "update", "delete"] # Adjust verbs based on the required access level
